/***************************************************************
 ***************************************************************
 ***************** This code was generated by ******************
 **************** angular-cli-library-generator ****************
 * https://www.npmjs.com/package/angular-cli-library-generator *
 ***************************************************************
 ***************************************************************
 ****** Changes to this file may cause incorrect behavior ******
 ********* and will be lost if the code is regenerated *********
 ***************************************************************
 ***************************************************************/

/* tslint:disable */
export const ROUTES = [
  { path: 'my-first-test', loadChildren: '../../components/my-first-test/my-first-test-demo#MyFirstTestDemoModule' },
  { path: 'my-second-test', loadChildren: '../../components/my-second-test/my-second-test-demo#MySecondTestDemoModule' }
];
/* tslint:enable */
